import sqlite3
import time
start_time=time.time()
conn = sqlite3.connect('test2.db')
c=conn.cursor()

'''
c.execute("CREATE TABLE transac(sno integer,c1 integer,c2 integer,c3 integer,c4 integer,c5 integer,c6 integer)")

c.execute("INSERT INTO  transac VALUES(1,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(2,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(3,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(4,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(5,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(6,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(7,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(8,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(9,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(10,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(11,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(12,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(13,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(14,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(15,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(16,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(17,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(18,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(19,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(20,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(21,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(22,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(23,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(24,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(25,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(26,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(27,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(28,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(29,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(30,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(31,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(32,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(33,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(34,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(35,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(36,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(37,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(38,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(39,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(40,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(41,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(42,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(43,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(44,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(45,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(46,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(47,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(48,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(49,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(50,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(51,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(52,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(53,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(54,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(55,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(56,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(57,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(58,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(59,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(60,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(61,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(62,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(63,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(64,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(65,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(66,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(67,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(68,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(69,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(70,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(71,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(72,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(73,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(74,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(75,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(76,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(77,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(78,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(79,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(80,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(81,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(82,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(83,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(84,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(85,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(86,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(87,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(88,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(89,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(90,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(91,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(92,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(93,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(94,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(95,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(96,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(97,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(98,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(99,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(100,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(101,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(102,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(103,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(104,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(105,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(106,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(107,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(108,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(109,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(110,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(111,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(112,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(113,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(114,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(115,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(116,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(117,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(118,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(119,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(120,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(121,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(122,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(123,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(124,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(125,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(126,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(127,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(128,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(129,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(130,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(131,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(132,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(133,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(134,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(135,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(136,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(137,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(138,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(139,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(140,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(141,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(142,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(143,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(144,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(145,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(146,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(147,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(148,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(149,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(150,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(151,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(152,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(153,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(154,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(155,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(156,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(157,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(158,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(159,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(160,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(161,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(162,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(163,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(164,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(165,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(166,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(167,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(168,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(169,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(170,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(171,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(172,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(173,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(174,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(175,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(176,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(177,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(178,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(179,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(180,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(181,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(182,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(183,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(184,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(185,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(186,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(187,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(188,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(189,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(190,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(191,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(192,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(193,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(194,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(195,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(196,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(197,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(198,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(199,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(200,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(201,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(202,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(203,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(204,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(205,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(206,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(207,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(208,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(209,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(210,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(211,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(212,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(213,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(214,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(215,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(216,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(217,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(218,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(219,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(220,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(221,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(222,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(223,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(224,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(225,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(226,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(227,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(228,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(229,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(230,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(231,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(232,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(233,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(234,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(235,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(236,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(237,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(238,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(239,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(240,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(241,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(242,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(243,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(244,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(245,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(246,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(247,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(248,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(249,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(250,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(251,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(252,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(253,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(254,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(255,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(256,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(257,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(258,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(259,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(260,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(261,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(262,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(263,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(264,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(265,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(266,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(267,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(268,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(269,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(270,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(271,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(272,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(273,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(274,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(275,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(276,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(277,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(278,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(279,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(280,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(281,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(282,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(283,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(284,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(285,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(286,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(287,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(288,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(289,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(290,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(291,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(292,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(293,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(294,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(295,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(296,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(297,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(298,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(299,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(300,4,5,6,null,null,null)")



c.execute("INSERT INTO  transac VALUES(301,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(302,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(303,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(304,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(305,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(306,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(307,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(308,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(309,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(310,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(311,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(312,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(313,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(314,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(315,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(316,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(317,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(318,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(319,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(320,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(321,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(322,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(323,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(324,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(325,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(326,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(327,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(328,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(329,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(330,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(331,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(332,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(333,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(334,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(335,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(336,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(337,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(338,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(339,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(340,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(341,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(342,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(343,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(344,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(345,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(346,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(347,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(348,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(349,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(350,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(351,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(352,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(353,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(354,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(355,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(356,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(357,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(358,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(359,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(360,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(361,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(362,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(363,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(364,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(365,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(366,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(367,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(368,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(369,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(370,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(371,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(372,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(373,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(374,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(375,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(376,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(377,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(378,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(379,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(380,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(381,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(382,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(383,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(384,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(385,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(386,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(387,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(388,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(389,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(390,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(391,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(392,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(393,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(394,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(395,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(396,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(397,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(398,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(399,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(400,4,5,6,null,null,null)")


c.execute("INSERT INTO  transac VALUES(401,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(402,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(403,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(404,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(405,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(406,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(407,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(408,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(409,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(410,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(411,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(412,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(413,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(414,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(415,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(416,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(417,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(418,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(419,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(420,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(421,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(422,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(423,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(424,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(425,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(426,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(427,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(428,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(429,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(430,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(431,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(432,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(433,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(434,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(435,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(436,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(437,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(438,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(439,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(440,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(441,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(442,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(443,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(444,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(445,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(446,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(447,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(448,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(449,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(450,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(451,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(452,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(453,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(454,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(455,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(456,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(457,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(458,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(459,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(460,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(461,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(462,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(463,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(464,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(465,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(466,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(467,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(468,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(469,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(470,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(471,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(472,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(473,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(474,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(475,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(476,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(477,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(478,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(479,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(480,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(481,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(482,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(483,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(484,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(485,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(486,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(487,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(488,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(489,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(490,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(491,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(492,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(493,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(494,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(495,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(496,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(497,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(498,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(499,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(500,4,5,6,null,null,null)")



c.execute("INSERT INTO  transac VALUES(501,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(502,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(503,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(504,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(505,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(506,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(507,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(508,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(509,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(510,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(511,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(512,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(513,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(514,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(515,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(516,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(517,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(518,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(519,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(520,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(521,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(522,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(523,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(524,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(525,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(526,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(527,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(528,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(529,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(530,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(531,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(532,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(533,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(534,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(535,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(536,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(537,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(538,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(539,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(540,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(541,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(542,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(543,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(544,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(545,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(546,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(547,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(548,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(549,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(550,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(551,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(552,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(553,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(554,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(555,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(556,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(557,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(558,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(559,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(560,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(561,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(562,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(563,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(564,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(565,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(566,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(567,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(568,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(569,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(570,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(571,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(572,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(573,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(574,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(575,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(576,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(577,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(578,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(579,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(580,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(581,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(582,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(583,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(584,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(585,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(586,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(587,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(588,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(589,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(590,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(591,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(592,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(593,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(594,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(595,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(596,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(597,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(598,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(599,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(600,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(601,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(602,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(603,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(604,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(605,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(606,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(607,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(608,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(609,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(610,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(611,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(612,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(613,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(614,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(615,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(616,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(617,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(618,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(619,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(620,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(621,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(622,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(623,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(624,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(625,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(626,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(627,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(628,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(629,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(630,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(631,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(632,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(633,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(634,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(635,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(636,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(637,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(638,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(639,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(640,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(641,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(642,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(643,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(644,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(645,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(646,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(647,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(648,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(649,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(650,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(651,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(652,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(653,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(654,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(655,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(656,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(657,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(658,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(659,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(660,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(661,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(662,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(663,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(664,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(665,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(666,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(667,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(668,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(669,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(670,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(671,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(672,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(673,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(674,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(675,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(676,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(677,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(678,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(679,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(680,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(681,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(682,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(683,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(684,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(685,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(686,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(687,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(688,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(689,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(690,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(691,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(692,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(693,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(694,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(695,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(696,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(697,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(698,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(699,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(700,4,5,6,null,null,null)")


c.execute("INSERT INTO  transac VALUES(701,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(702,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(703,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(704,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(705,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(706,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(707,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(708,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(709,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(710,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(711,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(712,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(713,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(714,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(715,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(716,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(717,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(718,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(719,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(720,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(721,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(722,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(723,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(724,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(725,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(726,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(727,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(728,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(729,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(730,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(731,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(732,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(733,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(734,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(735,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(736,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(737,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(738,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(739,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(740,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(741,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(742,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(743,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(744,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(745,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(746,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(747,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(748,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(749,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(750,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(751,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(752,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(753,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(754,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(755,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(756,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(757,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(758,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(759,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(760,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(761,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(762,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(763,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(764,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(765,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(766,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(767,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(768,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(769,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(770,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(771,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(772,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(773,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(774,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(775,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(776,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(777,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(778,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(779,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(780,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(781,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(782,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(783,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(784,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(785,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(786,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(787,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(788,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(789,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(790,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(791,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(792,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(793,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(794,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(795,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(796,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(797,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(798,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(799,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(800,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(801,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(802,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(803,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(804,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(805,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(806,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(807,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(808,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(809,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(810,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(811,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(812,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(813,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(814,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(815,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(816,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(817,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(818,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(819,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(820,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(821,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(822,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(823,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(824,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(825,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(826,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(827,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(828,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(829,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(830,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(831,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(832,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(833,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(834,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(835,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(836,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(837,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(838,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(839,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(840,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(841,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(842,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(843,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(844,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(845,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(846,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(847,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(848,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(849,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(850,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(851,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(852,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(853,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(854,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(855,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(856,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(857,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(858,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(859,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(860,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(861,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(862,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(863,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(864,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(865,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(866,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(867,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(868,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(869,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(870,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(871,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(872,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(873,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(874,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(875,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(876,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(877,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(878,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(879,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(880,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(881,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(882,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(883,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(884,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(885,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(886,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(887,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(888,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(889,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(890,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(891,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(892,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(893,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(894,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(895,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(896,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(897,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(898,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(899,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(900,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(901,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(902,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(903,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(904,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(905,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(906,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(907,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(908,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(909,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(910,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(911,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(912,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(913,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(914,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(915,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(916,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(917,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(918,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(919,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(920,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(921,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(922,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(923,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(924,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(925,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(926,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(927,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(928,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(929,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(930,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(931,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(932,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(933,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(934,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(935,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(936,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(937,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(938,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(939,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(940,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(941,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(942,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(943,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(944,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(945,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(946,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(947,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(948,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(949,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(950,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(951,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(952,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(953,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(954,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(955,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(956,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(957,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(958,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(959,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(960,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(961,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(962,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(963,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(964,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(965,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(966,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(967,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(968,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(969,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(970,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(971,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(972,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(973,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(974,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(975,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(976,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(977,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(978,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(979,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(980,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(981,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(982,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(983,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(984,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(985,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(986,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(987,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(988,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(989,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(990,4,5,6,null,null,null)")

c.execute("INSERT INTO  transac VALUES(991,1,2,5,6,null,null)")
c.execute("INSERT INTO  transac VALUES(992,2,4,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(993,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(994,1,2,4,6,null,null)")
c.execute("INSERT INTO  transac VALUES(995,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(996,2,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(997,1,3,6,null,null,null)")
c.execute("INSERT INTO  transac VALUES(998,1,2,3,5,6,null)")
c.execute("INSERT INTO  transac VALUES(999,1,2,3,6,null,null)")
c.execute("INSERT INTO  transac VALUES(1000,4,5,6,null,null,null)") 
'''

c.execute("select * from transac")

list_of_transactions=list(c.fetchall())

conn.commit()
conn.close()
def finding_c(l_list,l_count,c_list,c_count):
    for i in range(0,len(l_list)):
        for j in range(i+1,len(l_list)):
            p=[]
            p1=[]
            for k in range(0,len(l_list[i])):
                if l_list[i][k] not in p:
                    p.append(l_list[i][k])
            for k in range(0,len(l_list[j])):
                if l_list[j][k] not in p:
                    p.append(l_list[j][k])
            p=sorted(p)
            if p not in c_list:
                c_list.append(p)
                for k in range(0,len(l_count[i])):
                    if l_count[i][k] in l_count[j]:
                        p1.append(l_count[i][k])
                c_count.append(p1)
    temp=[]
    temp.append(c_list)
    temp.append(c_count)
    return temp
def finding_l(c_list,c_count_list,l_list,l_count_list):
    for i in range(0,len(c_list)):
        if len(c_count_list[i])>=1 and c_list[i] not in l_list:
            l_list.append(c_list[i])
            l_count_list.append(c_count_list[i])
    temp=[]
    temp.append(l_list)
    temp.append(l_count_list)
    return temp
#for each part we need to apply this method
def for_each_part(no_of_items,transaction_list_part,transaction_ids):
    c=[]
    #print("transaction list part entered the function ",transaction_list_part)
    #calculating the c1 seperately
    for i in range(0,no_of_items):
        l=[]
        l.append(i+1)
        c.append(l)
    c_count=[]
    for i in range(1,no_of_items+1):
        ids=[]
        for j in range(0,len(transaction_list_part)):
            if i in transaction_list_part[j]:
                ids.append(transaction_ids[j])
        c_count.append(ids)
    #print("c ",c)
    #print("c_count ",c_count)
    l=[]
    l_count=[]
    for i in range(0,6):
        l,l_count=finding_l(c,c_count,l,l_count)
        if len(l)==0:
            return []
        else:
            c,c_count=finding_c(l,l_count,c,c_count)
        #print("l ",l)
        #print("l_count ",l_count)
        #print("c ",c)
        #print("c_count ",c_count)
    temp=[]
    temp.append(l)
    temp.append(l_count)
    #print("temp in function ",temp)
    return temp
#Getting all the transactions into s
s=[]
for i in range(0,len(list_of_transactions)):
    t=[]
    for j in range(1,len(list(list_of_transactions)[i])):
        if list(list_of_transactions)[i][j]!=None:
            t.append(list(list_of_transactions)[i][j])
    s.append(t)
#Finding no. of items
no_of_items=0
items=[]
for i in range(0,len(s)):
    for j in range(0,len(s[i])):
        if s[i][j] not in items:
            items.append(s[i][j])
            no_of_items+=1
#Now we need to divide the list of transactions(i.e.... s) into parts
#dividing the entire list into 8 transactions and applying the method for_each_part
all_l=[]
all_l_count=[]
for i in range(0,len(s),10):
    transaction_ids=[]
    if i+8>=len(s):
        for j in range(i,i+10):
            transaction_ids.append(j)
        #print("for part 2")
        temp=for_each_part(no_of_items,s[i:],transaction_ids)
    else:
        for j in range(i,i+10):
            transaction_ids.append(j)
        #print("for part 1")
        temp=for_each_part(no_of_items,s[i:i+10],transaction_ids)
    #print("temp[0] ",temp[0])
    #print("temp[1] ",temp[1])
    #all l are present in temp[0]
    #all l_count of each corresponding l are present in temp[1]
    #let us take the minimum support count as 2
    if len(all_l)==0 and len(all_l_count)==0:
        #print("zero length")
        all_l.extend(temp[0])
        all_l_count.extend(temp[1])
    else:
        a_l=[]
        a_l_count=[]
        #Now we have to merge all_l and temp[0]
        # and all_l_count and temp[1]
        if len(all_l)<=len(temp[0]):
            for i in range(0,len(all_l)):
                if all_l[i] in temp[0]:
                    a_l.append(all_l[i])
                    a_l_count.append(list(set(all_l_count[i]+temp[1][i])))
                else:
                    a_l.append(all_l[i])
                    a_l_count.append(all_l_count[i])
            for i in range(0,len(temp[0])):
                if temp[0][i] not in a_l:
                    a_l.append(temp[0][i])
                    a_l_count.append(temp[1][i])
        else:
            for i in range(0,len(temp[0])):
                if temp[0][i] in all_l:
                    a_l.append(temp[0][i])
                    a_l_count.append(list(set(all_l_count[i]+temp[1][i])))
                else:
                    a_l.append(temp[0][i])
                    a_l_count.append(temp[1][i])
            for i in range(0,len(all_l)):
                if all_l[i] not in a_l:
                    a_l.append(all_l[i])
                    a_l_count.append(all_l_count[i])
        all_l=a_l
        all_l_count=a_l_count
        #print("all_l ",all_l)
        #print("all_l_count ",all_l_count)
#now optiminzing the all_count and all_l_count
min_support=int(input("Enter the threshold for the support count"))
final_l=[]
final_l_count=[]
for i in range(0,len(all_l_count)):
    if len(all_l_count[i])>=min_support:
        final_l.append(all_l[i])
        final_l_count.append(all_l_count[i])
#print("final_l ",final_l)
#print("final_l_count ",final_l_count)
#Now we need to remove all the subsets of frequently repeating pattern and print the most frequently repeating pattern
res_l=[]
res_l_count=[]
for i in range(0,len(final_l)):
    f=0
    for j in range(i+1,len(final_l)):
        c=0
        for k in range(0,len(final_l[i])):
            if final_l[i][k] in final_l[j]:
                c+=1
        if c==len(final_l[i]):
            f=1
    if f==0:
        res_l.append(final_l[i])
        res_l_count.append(final_l_count[i])
print("Congo the most frequently repeating patterns are")
print(res_l)
print("they are found in the transactions respectively")
print(res_l_count)
print(time.time()-start_time)